name: CodeCraft
markdown: kramdown
future: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

highligher: true
permalink: /events/:year/:month/:title
gems:
  - jekyll-redirect-from


title: CodeCraft
url: http://www.codecraftuk.org
description: "We are a software crafters meetup. We discuss, demonstrate and debate how to write well-structured, malleable software."
